### PR TITLE
Support NPM installation and AMD/CommonJS environments

### PR DESCRIPTION
**Pull request by maxenglander**
Hey @cuddergambino these are some changes I made in order to use the library in our NPM/CommonsJS environment. By no means a show-stopper if these doesn't work for you but thought you might be interested.

### CODE REVIEW

**Comment by cuddergambino** [comment]
@maxenglander thanks! I will look it over soon

**Comment by maxenglander** [comment]
Thanks @cuddergambino! Just FYI I also added the ability to send requests asynchronously, which became necessary when Dopamine started timing out today. Can close this PR and re-open two separate PRs if you prefer.

**Comment by cuddergambino** [comment]
I finished review and forgot to merge it yesterday! I've merged the first PR, please make another PR as usual for the async calls

**Comment by maxenglander** [comment]
@cuddergambino Unfortunately when I pushed to my fork it got include in this PR. So you've already merged it! If it doesn't look good to you, you can revert the last commit.

**Pull request merged**
